{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "7d12a7d1_6e0a3d2c",
        "filename": "occ_status.cpp",
        "patchSetId": 32
      },
      "lineNbr": 479,
      "author": {
        "id": 1000238
      },
      "writtenOn": "2022-04-01T22:42:17Z",
      "side": 1,
      "message": "Instance still not added here, but not a big deal",
      "revId": "373af75721778bd6fac65d5cf54a982506d64bfe",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "7f4f0777_d64fa380",
        "filename": "occ_status.cpp",
        "patchSetId": 32
      },
      "lineNbr": 479,
      "author": {
        "id": 1001035
      },
      "writtenOn": "2022-04-04T13:15:53Z",
      "side": 1,
      "message": "I did that, must have reverted when I copid to get the ERR,,, I will push that into my next story...",
      "parentUuid": "7d12a7d1_6e0a3d2c",
      "revId": "373af75721778bd6fac65d5cf54a982506d64bfe",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}